### ISSUE TITLE
Colorize terminal output

### ISSUE THREAD

**Issue by arusahni** [arusahni/git-req#12]
It'd be nice if both errors and positive outcomes resulted in colorful text being printed to the terminal.

**Comment by undef1nd** [comment]
Hey @arusahni , I’d like to take a look at this one.

**Comment by arusahni** [comment]
Hi @undef1nd. That'd be awesome!  Once/If you select a library, can you run it past me for approval?  Also, it'd be nice if we could colorize the `--list` output, too.

**Comment by undef1nd** [comment]
Sure thing, @arusahni! I’m pretty sure I’ll have some questions as I’m a newbie. Thanks!

**Comment by undef1nd** [comment]
@arusahni , I've researched a bit `colored` crate seems to be the easiest to use, also there's `termion` crate.
But to be honest, I'm not sure how any of these will work with `list_open_requests` output https://github.com/arusahni/git-req/blob/master/src/main.rs#L122-L124

**Comment by arusahni** [comment]
`colored` looks like a solid choice. Good luck!

**Comment by undef1nd** [comment]
Related PR #36

**Comment by arusahni** [comment]
That it is!
