### ISSUE TITLE
Homebrew package

### ISSUE THREAD

**Issue by arusahni** [arusahni/git-req#16]
Let's distribute on Homebrew to provide an upgrade path.

**Comment by bobbo** [comment]
Hi, I'm interested in taking a look at this for Hacktoberfest.

**Comment by arusahni** [comment]
@bobbo that sounds awesome! Happy hacking! :shipit:

**Comment by bobbo** [comment]
Hey @arusahni. I've been looking into the guidelines for getting this into Homebrew core. They suggest having at least 50 GitHub stars to prove "notability", but there's no harm in trying. Alternatively we could set-up a tap repo (probably under your name) so the install process would be `brew tap arusahni/git-req && brew install git-req`, which isn't as ideal, but isnt a disaster. 

Having the Brew formula ready to go in any case will be a good win.

**Comment by arusahni** [comment]
Definitely no harm in trying.  That being said, I'm not averse to a tap - the main reasons I'd like to package this are ease of installation and upgrade. A tap gets the project a lot closer than things are right now :-)

What's the recommended practice for maintaining a tap repo? A separate `git-req-tap` repo that I push `git-req/master` to whenever I cut a release? 

A Brew formula would definitely be a win.  Thanks for looking into this!

**Comment by eugene-babichenko** [comment]
Creating a tap repo requires to create a repo named `homebrew-tap`. This repo will store all of your taps. Maintaining that is pretty easy, you just push updated formulas to that repo. I case you use Github releases you formulas are just redirects for macOS builds. For instance, that's how it looks for my pet project https://github.com/eugene-babichenko/homebrew-tap/blob/master/Formula/zpm.rb

@bobbo don't you mind me helping with this repo?

@arusahni didn't find that in issues, but I would also like to see a feature like `list-prs` which will list pull requests along with their numbers. What do you think of it?

**Comment by bobbo** [comment]
@eugene-babichenko We may not need to go down the tap route. I've written & been testing a Homebrew formula for this, I'll put it in a PR soon. That can be submitted to the homebrew core, there are a bunch of rust tools. I think it's worth trying to see if we can get in there before deciding to maintain a tap. Will drop the PR soon.

**Comment by bobbo** [comment]
Ok, so I submitted to homebrew-core but the PR was closed for notability, like we kind of expected. So the tap route is the best solution for now. @eugene-babichenko, your experience will come in handy here!

The PR reviewer pointed at https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap for some more info

**Comment by arusahni** [comment]
Thanks for running with this! Question: if this package eventually meets the criteria for being included in homebrew-core, what happens to existing tap users? Does the higher-versioned package in core win? Do they need to un-tap the keg?

**Comment by bobbo** [comment]
@arusahni, good question! From https://docs.brew.sh/Taps#formula-with-duplicate-names, it looks like -core overrides any tap. But if (/when 😉) it's in core, it would make sense to include instructions to remove a tap if people have it. And/or have the tapped formula spit out a deprecation warning with instructions.

**Comment by arusahni** [comment]
@bobbo I've merged the formula - thanks for making it!

@eugene-babichenko: if you're interested in getting some Hacktoberfest credit, I've created a repository for the tap at https://github.com/arusahni/homebrew-git-req that needs a PR with the formula.
