### ISSUE TITLE
Generate completions and man page with build

### ISSUE THREAD

**Issue by arusahni** [arusahni/git-req#35]
A fun side-effect of being a git extension is that git gobbles the `--help` flag and seems to forwards it on to a man page for the extension. Since `git-req` doesn't bundle one, it fails to find the documentation.  Additionally, `git-req` uses clap. It'd be nice if it exported completions for Bash and Zshell.

* Have a man page generated by the build.
* Have shell completions generated by the build.

**Comment by luxrck** [comment]
@arusahni Hello, could I take this up ?

**Comment by arusahni** [comment]
Hi @luxrck - sure thing! Let me know if you have any questions

**Comment by luxrck** [comment]
Sorry for taking this too long...... pr #39 should fix this.

**Comment by arusahni** [comment]
No worries - thanks for the PR! I should get to the review over the next few days - this week was busier than expected :grimacing:
