### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by jaykwon** [arusahni/git-req#6]
When trying to utilize Python 3.6, the following error spits out:

```python
  File "<string>", line 1
    from __future__ import print_function; import sys, re; print(re.search(ur'((http[s]?|ssh):\/\/)?(\S+@)?(([^:\/])+)', sys.stdin.read()).group(4))
                                                                                                                      ^
SyntaxError: invalid syntax
```

**Comment by arusahni** [comment]
Thanks for the reminder! I was testing this fix locally, but hadn't committed and pushed it, yet.  It should be fixed in [HEAD](https://github.com/arusahni/git-req/commit/793a68093733379448f5515b6b94befcc96b4976).

**Comment by jaykwon** [comment]
Confirmed as solved in a Python 3 project. Thanks!
