### ISSUE TITLE
New release to update smallvec version?

### ISSUE THREAD

**Issue by 5225225** [arusahni/git-req#68]
Hello!

I'm coming to this crate from https://github.com/rust-lang/rust/pull/99389, where the checks for uninit data are being made stricter. This crate git's version works fine under the stricter checks in that PR, but the version on crates.io doesn't, since the bump of smallvec hasn't been published.

**Comment by arusahni** [comment]
Thanks for reaching out! I have published a maintenance release containing the fix.
