### ISSUE TITLE
Error thrown with GitLab >11

### ISSUE THREAD

**Issue by oxhacks** [arusahni/git-req#7]
When attempting to switch branches with a GitLab 11.3 instance, I get the following error:

```git
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 0

remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 2 (delta 1), reused 0 (delta 0)
Unpacking objects: 100% (2/2), done.
From <redacted>
   abcdefg..1234567  master     -> origin/master
fatal: Needed a single revision
Could not find remote branch
```

Python Version: 3.6.5
VCS System: GitLab
VCS Version: 11.3

**Comment by arusahni** [comment]
Switch repos or switch branches?

**Comment by oxhacks** [comment]
Confirmed here - looks like they just deprecated v3 as of 11.0.

```{"error":"API V3 is no longer supported. Use API V4 instead."}```

https://docs.gitlab.com/ee/api/v3_to_v4.html

**Comment by arusahni** [comment]
Thanks for your patience - I just released v1.0.0 of this script that drops GitLab v3 support in favor of v4. LMK if it addresses your issue - if so, I'll close this ticket.

**Comment by oxhacks** [comment]
On the latest build, getting this error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'source_branch'
```

Thanks for looking into this!

**Comment by arusahni** [comment]
Could you uncomment https://github.com/arusahni/git-req/blob/master/git-req#L16 and share what the response looks like on https://github.com/arusahni/git-req/blob/master/git-req#L107 ?  Feel free to redact as much as you'd like - I'm more interested in the general schema.

I made some changes there to support the new v4 schema that returned an object instead of an array, which worked for my gitlab.com test case, but may be different for older/hosted versions?

**Comment by oxhacks** [comment]
After uncommenting https://github.com/arusahni/git-req/blob/master/git-req#L107, I see this:
```json
{"message":"404 Project Not Found"}
```
Additionally I do see the Project ID and Request Number in `set -x`:
```
++ PROJECT_ID=429
++ REQ_NUM=1580
```

**Comment by oxhacks** [comment]
I'm good with standing down then. Just to confirm, I tried this on a project with a bare `.git/config` section for `req`, and thinks worked okay.

Thanks for chasing this down! Look forward to v2.
